apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: pvs
type: Opaque
stringData:
  mysql-root-password: rootpass
  mysql-user-password: verpass
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: pvs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-root-password
            - name: MYSQL_DATABASE
              value: verification
            - name: MYSQL_USER
              value: veruser
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-user-password
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-pvc
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-pvc
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: pvs
spec:
  ports:
    - port: 3306
  selector:
    app: mysql
  type: ClusterIP
